name: Release

on:
  push:
    branches:
      - main

jobs:
  analyze:
    uses: SP-Packages/actions/.github/workflows/code-quality.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      slug: SP-Packages/printer
    permissions:
      contents: read
      pull-requests: write

  prepare:
    needs: analyze
    uses: SP-Packages/actions/.github/workflows/semantic-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

  rebase:
    needs: prepare
    uses: SP-Packages/actions/.github/workflows/rebase-develop.yml@main
    permissions:
      contents: write
